# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47569272d20199865f13bd0478b7da62e8fa051530ca09319724b8f31c01e4d7428fe1621e0c8fe9c52e0c08e17d37055f80c5166551a03cb1ec78ff2b622c0e

test:
  secret_key_base: 82dcbe8f896a7b1f79b3a2bc7f8da39204745423a3d0da250365399314e080d82b648e6782d0c98836ffe9f168f4904be9b4db1953babdae4fe34b677d863b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
